---
- name: install nginx
  yum: name=nginx state=installed

- name: setup nginx default page
  template: src=../templates/index.html dest=/usr/share/nginx/html owner=root group=root mode=0644

- name: setup nginx config
  template: src=../templates/nginx.conf dest=/etc/nginx/nginx.conf owner=root group=root mode=0644

- name: start nginx
  service: name=nginx state=running enabled=yes
