---
- hosts: all
  name: do stuff common to all servers
  become: yes
  become_method: sudo

  roles:
    # install epel using third party module
    - { role: sfromm.epel }
    - user_rcfiles
    - selinux_disable
    - standard_packages
